### ISSUE TITLE
Augment the Istio Chart to Allow Use of Jaeger

### ISSUE THREAD

**Issue by davidvonthenen** [thecodeteam/roadmap#233]
Implement the ability for the Istio chart to deploy a production Jaeger instance in the form of a helm chart instead of using/deploying the default Zipkin instance.

**Comment by dvonthenen** [comment]
Finished implementation... began testing.

Will need to submit 2 PRs as implemented for:
- Allow the Jaeger component names to allow for overriding. This is used so that the jaeger components can match the naming convention of the Istio components.
- Allow Jaeger to be deployed instead of using/deploying the default Zipkin instance
